Cypress.Commands.add("details", (bannerPosition, header, modelData) => {
      cy.get('.banner-button')
      .eq(bannerPosition)
      .click()
    cy.get('button')
      .contains('Details')
      .click()
    cy.get('h1')
      .contains(header)
      .should('be.visible')
    const fiveStars = modelData.getDrops(5).map(item => item.name)
    cy.get('table')
      .first()
      .within(() => {
        cy.get('tbody > tr > td')
          .then($td => [...$td].filter(item => item.innerText !== 'Character' && item.innerText !== 'Weapon'))
          .each(($td, i) => {
            expect($td.text()).to.equal(fiveStars[i])
          })
      })
    const fourStars = modelData.getDrops(4).map(item => item.name)
    cy.get('table')
      .eq(1)
      .within(() => {
        cy.get('tbody > tr > td')
          .then($td => [...$td].filter(item => item.innerText !== 'Character' && item.innerText !== 'Weapon'))
          .each(($td, i) => {
            expect($td.text()).to.equal(fourStars[i])
          })
      })
    const threeStars = modelData.getDrops(3).map(item => item.name)
    cy.get('table')
      .last()
      .within(() => {
        cy.get('tbody > tr > td')
          .then($td => [...$td].filter(item => item.innerText !== 'Character' && item.innerText !== 'Weapon'))
          .each(($td, i) => {
            expect($td.text()).to.equal(threeStars[i])
          })
      })
})

Cypress.Commands.add("wish", banner => {
  cy.get(`.banner-button.${banner}`)
    .click()
  cy.get('.wish-button')
    .contains('Wish x10')
    .click()
  cy.get('.skip-button')
    .click()
  cy.get('.close-button')
    .click()
})
